<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Modules\Core\Settings\GeneralSettings;

class ApplicationSupportSeeder extends Seeder
{
    public function run(GeneralSettings $settings): void
    {
        $settings->name = 'Teachify';
        $settings->tagline = 'Private teaching management';
        $settings->contact_email = 'teacher@teachify.test';
        $settings->contact_phone = '01000000000';
        $settings->address = 'Demo learning center';
        $settings->city = 'Cairo';
        $settings->country = 'Egypt';
        $settings->facebook_url = 'https://facebook.com/teachify';
        $settings->instagram_url = 'https://instagram.com/teachify';
        $settings->linkedin_url = 'https://linkedin.com/company/teachify';
        $settings->youtube_url = null;
        $settings->website_url = 'https://teachify.test';
        $settings->timezone = 'Africa/Cairo';
        $settings->locale = 'en';
        $settings->report_footer_text = 'Generated by Teachify.';
        $settings->show_logo_on_reports = true;
        $settings->save();

        Cache::put('teachify.seeded_at', now()->toIso8601String(), now()->addWeek());

        DB::table('cache')->updateOrInsert(
            ['key' => 'teachify_seeded_at'],
            [
                'value' => serialize(now()->toIso8601String()),
                'expiration' => now()->addWeek()->timestamp,
            ],
        );

        DB::table('cache_locks')->updateOrInsert(
            ['key' => 'teachify_seed_lock'],
            [
                'owner' => 'database-seeder',
                'expiration' => now()->addMinutes(5)->timestamp,
            ],
        );
    }
}
