<?php

use Spatie\LaravelSettings\Migrations\SettingsMigration;

return new class extends SettingsMigration
{
    public function up(): void
    {
        $this->migrator->add('general.name', 'Teachify');
        $this->migrator->add('general.tagline', 'Private teaching management');
        $this->migrator->add('general.contact_email', 'teacher@teachify.test');
        $this->migrator->add('general.contact_phone', null);
        $this->migrator->add('general.address', null);
        $this->migrator->add('general.city', null);
        $this->migrator->add('general.country', null);
        $this->migrator->add('general.facebook_url', null);
        $this->migrator->add('general.instagram_url', null);
        $this->migrator->add('general.linkedin_url', null);
        $this->migrator->add('general.youtube_url', null);
        $this->migrator->add('general.website_url', null);
        $this->migrator->add('general.timezone', 'Africa/Cairo');
        $this->migrator->add('general.locale', 'en');
        $this->migrator->add('general.report_footer_text', 'Generated by Teachify.');
        $this->migrator->add('general.show_logo_on_reports', true);
    }
};
