<?php

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Inertia\Testing\AssertableInertia as Assert;
use Modules\Core\Models\SettingMedia;
use Modules\Core\Settings\GeneralSettings;

uses(RefreshDatabase::class);

it('allows a teacher to view and update core settings', function () {
    $teacher = User::factory()->teacher()->create();

    $this->actingAs($teacher)
        ->get(route('admin.settings.edit'))
        ->assertOk()
        ->assertInertia(fn (Assert $page) => $page
            ->component('Admin/Settings/Edit')
            ->has('settings')
            ->has('media')
            ->has('timezones')
            ->where('action', route('admin.settings.update')));

    $this->actingAs($teacher)
        ->put(route('admin.settings.update'), validSettingsPayload([
            'name' => 'Teachify Academy',
            'contact_email' => 'hello@teachify.test',
            'facebook_url' => 'https://facebook.com/teachify-academy',
            'show_logo_on_reports' => '1',
        ]))
        ->assertRedirect(route('admin.settings.edit'));

    $settings = app(GeneralSettings::class);

    expect($settings->name)->toBe('Teachify Academy')
        ->and($settings->contact_email)->toBe('hello@teachify.test')
        ->and($settings->facebook_url)->toBe('https://facebook.com/teachify-academy')
        ->and($settings->show_logo_on_reports)->toBeTrue();
});

it('blocks parents from core settings', function () {
    $parent = User::factory()->parent()->create();

    $this->actingAs($parent)
        ->get(route('admin.settings.edit'))
        ->assertForbidden();
});

it('stores logo uploads in a single media collection item', function () {
    Storage::fake('public');
    $teacher = User::factory()->teacher()->create();

    $this->actingAs($teacher)
        ->put(route('admin.settings.update'), validSettingsPayload([
            'logo' => UploadedFile::fake()->image('logo-one.png', 200, 100),
        ]))
        ->assertRedirect(route('admin.settings.edit'));

    expect(SettingMedia::brand()->getMedia('logo'))->toHaveCount(1);

    $this->actingAs($teacher)
        ->put(route('admin.settings.update'), validSettingsPayload([
            'logo' => UploadedFile::fake()->image('logo-two.png', 200, 100),
        ]))
        ->assertRedirect(route('admin.settings.edit'));

    $media = SettingMedia::brand()->getMedia('logo');

    expect($media)->toHaveCount(1)
        ->and($media->first()->file_name)->toBe('logo-two.png');
});

function validSettingsPayload(array $overrides = []): array
{
    return array_merge([
        'name' => 'Teachify',
        'tagline' => 'Private teaching management',
        'contact_email' => 'teacher@teachify.test',
        'contact_phone' => '01000000000',
        'address' => 'Demo learning center',
        'city' => 'Cairo',
        'country' => 'Egypt',
        'facebook_url' => 'https://facebook.com/teachify',
        'instagram_url' => 'https://instagram.com/teachify',
        'linkedin_url' => 'https://linkedin.com/company/teachify',
        'youtube_url' => 'https://youtube.com/@teachify',
        'website_url' => 'https://teachify.test',
        'timezone' => 'Africa/Cairo',
        'locale' => 'en',
        'report_footer_text' => 'Generated by Teachify.',
        'show_logo_on_reports' => '1',
    ], $overrides);
}
